### ISSUE TITLE
Fail to download the dataset

### ISSUE THREAD

**Issue by gogojjh** [BAILOOL/PlaceRecognition-LoopDetection#2]
We failed to download the PlaceRecognition and LoopDetection dataset on http://143.248.39.254/PlaceRecognition.zip, http://143.248.39.254/LoopDetection.zip.
Would you mind checking them?
Thanks!

**Comment by BAILOOL** [comment]
@gogojjh Indeed we have started to reinstall that server on Thursday. The plan is to bring everything back before Monday/Tuesday. We are very sorry for the inconvenience. I will let you know whenever it is up right away!

**Comment by gogojjh** [comment]
Thanks a lot!

**Comment by gogojjh** [comment]
By the way, regarding your paper, I fell confused about the "search window size k". Could you please explain the function of k in the creation of database and road markings matching respectively? I also fell confused about the fig.2. What did the X-axis mean?
Thanks, I am looking forward to your reply.

**Comment by BAILOOL** [comment]
@gogojjh the server seems to be up and the data should be available through the original links. 

Actually Fig. 2 is just an example of a sequence of road markings which are encountered while driving on the road. The distance in meters on the X-axis shows the relative distance (current and previous) road markings.

The search windows size parameter *k* corresponds to how many road markings are used for place localization/loop detection. So basically we drive around, we encounter a road marking and add it to the database. We drive further, we encounter another road marking, so we add it to the existing sequences in the database (if their length is still less than *k*) and create a new sequence with a current road marking as the beginning of the sequence. So when a sequence in the database reaches the length of *k*, it is blocked for further write (i.e. add) operation, and only available for the read (i.e. checking road markings and relative distances between sequences) one.

**Comment by gogojjh** [comment]
Thanks! After reading your code, I understand your work.
By the way, will you opensource the code of your previous work: "Robust road marking detection & recognition using density-based grouping & machine learning techniques"?

**Comment by BAILOOL** [comment]
@gogojjh Great to hear that. There was always a goal to open source the code for the road marking recognition paper. But the code was always written in a very research-style manner and was never rewritten for the production purposes. I think I will try to open source it but that's definitely will take some time. I will let you know when it is done. Are you planning to use it if it is available?
