### ISSUE TITLE
Fail to download the datasets

### ISSUE THREAD

**Issue by zhanqan** [BAILOOL/PlaceRecognition-LoopDetection#3]
Your datasets is unavailable, and I faied to ping your ip address http://143.248.39.254

**Comment by rameau-fr** [comment]
Sorry for the inconvenience, we disconnected our server temporarily. The data should be available after next Friday (due to vacations season).

**Comment by zhanqan** [comment]
Thanks a lot!!!

**Comment by BAILOOL** [comment]
@zhanqan Links to the data are updated. Good luck!
